development:
  bucket: development_sanci
  access_key_id: AKIAICDXU5SXRWQA5RQA
  secret_access_key: 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
test:
  bucket: development_sanci
  access_key_id: AKIAICDXU5SXRWQA5RQA
  secret_access_key: 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
production:
  bucket: development_sanci
  access_key_id: AKIAICDXU5SXRWQA5RQA
  secret_access_key: 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